version: "3"

services: 
  api:
    container_name: "pp-api"
    build: 
      context: ./server
      target: release
    image: leunardo/sample-app-server

    ports:
        - "3000:3000"
    
    environment: 
      - PORT=3000

  web:
    container_name: "pp-web"
    build: 
      context: ./app
      target: release
    image: leunardo/sample-app-web

    ports:
      - "4200:4200"

  proxy:
    container_name: "pp-proxy"
    build:
      context: ./proxy
    image: leunardo/sample-app-proxy

    ports:
      - "80:80"