version: "3"

services: 
  api:
    container_name: "pp-api"
    build: 
      context: ./server
      target: development
    volumes:
      - ./server:/server

    ports:
        - "3000:3000"
    
    environment: 
      - PORT=3000

  web:
    container_name: "pp-web"
    build: 
      context: ./app
      target: development
    volumes:
      - ./app/src:/app/src

    ports:
      - "4200:4200"