version: "3"

services: 
  api:
    container_name: "api"
    build: 
      context: ./server
      target: development
    volumes:
      - ./server:/server

    ports:
        - "3000:3000"
    
    environment: 
      - PORT=3000
