FROM node:current-alpine as development

WORKDIR /app/

COPY ./package.json /app/
COPY ./package-lock.json /app/

RUN npm install
COPY . /app/

ENTRYPOINT [ "npm", "start" ]


FROM development as build
RUN npm run build


FROM nginx:stable-alpine as release
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/app /usr/share/nginx/html
RUN echo "Starting service..."
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]

