FROM node:current-alpine as development

COPY . /server/
WORKDIR /server/

RUN npm install
RUN npm install nodemon
ENTRYPOINT [ "npm", "start" ]


FROM development as release
ENTRYPOINT [ "node", "src/main.js" ]
